# Day 3 - intoduction to R

**Learning Goals:**

By the end of today's session, students will be able to: 

* Navigate the RStudio environment and move between the different panels.
* Open, save, and run an Rmd (R Markdown) file within RStudio.
* Apply internet searches, help functions, and documentation to learn to use the appropriate functions. 
* Assign and manipulate variables within the current environment/session in R.
* Create, modify, and access into a vector (an ordered grouping of elements).
* Create, modify, and access into a dataframe (an ordered two-dimensional grouping of elements with rows and columns).
* Apply existing functions to accomplish a specific task in R. 

**Preparing for Today:**
Please read through all parts of Section 1: Workshop Introduction.

Before you start reading through Section 2 for today or taking part in synchronous activities, download and [open today's worksheet](https://github.com/darachm/dll-r/blob/main/worksheets/dll-r_Day3_Lab.Rmd). On this Github page, please right-click the button that says "Raw" and click "Save Link As..." to get a local copy of this Rmd file on your computer and open it in Rstudio.

**Today's Schedule:**

|   Start Time  |   End Time  |   Activity    |          Description          |   Facilitator   |
| ------------- | ----------- | ------------- | ----------------------------- | --------------- |
| 10:00 AM PDT  | 10:45 AM PDT| Synchronous   | Welcome session on Zoom       | **Melissa**, Samson, Margaret, Darach, Zac  |
| 10:45 AM PDT  | 11:30 AM PDT| Asynchronous  | Work through [sections 2.1-2.3](https://darachm.github.io/dll-r/navigating-rstudio.html) | ??? |
| 11:30 AM PDT  | 12:15 PM PDT| Synchronous   | Peer coding exercises on Zoom | **Melissa**, Samson, Darach, Zac  |
| 12:15 PM PDT  | 12:45 PM PDT| Lunch Break   | Take a computer break!        |       N/A       |
| 12:45 PM PDT  | 1:30 PM PDT | Asynchronous  | Work through [sections 2.4-2.5](https://darachm.github.io/dll-r/working-with-vectors.html) | ??? |
| 1:30 PM PDT   | 2:30 PM PDT | Synchronous   | Peer coding exercises on Zoom | **Melissa**, Samson, Darach, Zac  |
| 2:30 PM PDT   | 3:00 PM PDT | Snack Break   | Take a computer break!        |       N/A       |
| 3:00 PM PDT   | 3:30 PM PDT | Synchronous   | Wrap-up session on Zoom       |   **Samson**, Margaret, Darach, Zac   |
