# Day 4 - tidyverse and visualizations

**Learning Goals:**

By the end of today's session, students will be able to: 

* Read in and process data starting from a local saved file
* Transform, scale, filter, and convert values within a dataset
* Describe the roles of data, aesthetics, and geoms in ggplot functions.
* Choose the correct aesthetics and alter the geom parameters for a scatter plot, histogram, or box plot.
* Customize plot scales, titles, subtitles, themes, fonts, layout, and orientation.
* Layer multiple geoms in a single plot, including error bars for data analysis.
* Save a ggplot to a local file.
* Analyze dataset using a variety of statistical approaches.

**Preparing for Today:**
Please make sure you have completed all readings and activities from Section 2: Day 3 - introduction to R. You will also have some time at the start of the day to do the first sections 3.1-3.3.

Before you start reading through Section 3 for today or taking part in synchronous activities, download and [open today's worksheet](https://github.com/darachm/dll-r/blob/main/worksheets/dll-r_Day4_Lab.Rmd). On this Github page, please right-click the button that says "Raw" and click "Save Link As..." to get a local copy of this Rmd file on your computer and open it in Rstudio.


**Today's Schedule:**

|   Start Time  |   End Time  |   Activity    |          Description          |   Facilitator   |
| ------------- | ----------- | ------------- | ----------------------------- | --------------- |
| 10:00 AM PDT  | 10:45 AM PDT| Asynchronous  | Work through [sections 3.1-3.3](https://darachm.github.io/dll-r/reading-and-processing-data.html) | **Margaret** |
| 10:45 AM PDT  | 11:30 AM PDT| Synchronous   | Peer coding exercises on Zoom | **Margaret**, Melissa, Samson, Zac |
| 11:30 AM PDT  | 12:15 PM PDT| Asynchronous  | Work through [sections 3.4-3.5](https://darachm.github.io/dll-r/making-plots-with-ggplot2.html) | **Melissa**, Margaret |
| 12:15 PM PDT  | 12:45 PM PDT| Lunch Break   | Take a computer break!        |       N/A       |
| 12:45 PM PDT  | 1:30 PM PDT | Synchronous   | Peer coding exercises on Zoom | **Melissa**, Margaret, Zac    |
| 1:30 PM PDT   | 2:00 PM PDT | Asynchronous  | Work through [sections 3.6](https://darachm.github.io/dll-r/applying-basic-stats.html)     | Margaret |
| 2:00 PM PDT   | 2:30 PM PDT | Snack Break   | Take a computer break!        |       N/A       |
| 2:30 PM PDT   | 3:30 PM PDT | Synchronous   | Wrap-up session on Zoom       |       **Samson**, Margaret, Zac       |
