---
title: "Day 5 - building workflows, loops, using packages, and finding help in new areas"
---

# Day 5 - workflows, loops, packages, and help

Today we're going to learn about applying these R 
skills to 
repeat, reproduce, extend, and share your analyses.

First, let's review the last two days.

<!-- exercise -->

<!--are we trying to make students think about writing functions and clean code? I'm not sure that's clear if this is asynchronous reading-->

- What have we done?
- Crack open your code - can you use it again?
- Can you adapt it to modify your question, 
  feed in new data, and modify the
  scientifically-important bits easily?
- Can you share it with someone and they follow
  along?

---

Our goals are to learn how to:

- organize work in a folder and rmarkdown files
- build a workflow analyzing some viral proteins in a *scalable* way
- modify our workflow to expand the analyses
- obtain and use packages to user other people's work
- tackling new problems with new R packages

---

**Preparing for Today:**
Please make sure you have completed all readings and activities from 
Section 3: Day 4 - tidyverse and visualizations. 

Before you start reading through Section 4 for today or taking part in
synchronous activities, download and [open today's
worksheet](https://github.com/darachm/dll-r/blob/main/worksheets/dll-r_Day5_Lab.Rmd).
On this Github page, please right-click the button that says "Raw" and click
"Save Link As..." to get a local copy of this Rmd file on your computer and
open it in Rstudio.

**Today's Schedule:**

| Start Time | End Time | Activity |   Description   | Facilitator |
| ------------- | ----------- | ------------- | ----------------------------- | --------------- |
| 10:00 AM PDT | 10:15 AM PDT | Synchronous - lecture, groups | Intro | Darach, Melissa, Samson, Margaret |
| 10:15 AM PDT | 10:45 AM PDT | Synchronous - lecture, groups | 4.1 Organizing workflows, more rmarkdown | Darach, Melissa, Samson, Margaret |
| 10:45 AM PDT | 11:15 AM PDT | Asynchronous - video, slack, etc | 4.2 Project - analyze viral protein sequences | Darach, Samson, Margaret |
| 11:15 AM PDT | 11:45 AM PDT | Synchronous - lecture, groups | 4.2 Extending the analysis to look for motifs ... and what else? string data? | Darach, Melissa, Samson, Margaret |
| 11:45 AM PDT | 12:15 PM PDT | Asynchronous - video, slack, etc | 4.2 Project - analyze viral protein sequences | Darach, Samson, Margaret |
| 12:15 PM PDT | 12:45 PM PDT | Break | Take a computer break!  |  N/A  |
| 12:45 PM PDT | 01:00 PM PDT | Synchronous - lecture | 4.3 Packages - why and how | Darach, Samson, Margaret |
| 12:45 PM PDT | 01:15 PM PDT | Asynchronous - video, slack, etc | 4.3 Packages - install stuff | Darach, Samson, Margaret |
| 01:15 PM PDT | 01:45 PM PDT | Synchronous - lecture, groups | 4.4 Demo/discuss some places to find help | Darach, Samson, Margaret |
| 01:45 PM PDT | 02:30 PM PDT | Synchronous - groups | 4.4 Attempt ambitious tutorials | Darach, Samson, Margaret |
| 02:30 PM PDT | 02:45 PM PDT | Synchronous - lecture, groups | 4.5 Writing nice code (if time) | Darach, Samson, Margaret |
| 02:45 PM PDT | 03:00 PM PDT | Synchronous - discussion | 4.6 Wrapping up | Darach, Samson, Margaret |

<!-- -->

