--- 
title: "DLL 2021, R section"
author: 
    - "mesako"
    - "Margaret"
    - "Samson"
    - "Zac"
    - "darachm"
date: "Typeset on `r Sys.Date()`"
output:
  bookdown::gitbook:
    css: style.css
    config:
      toc:
        before: |
          <li><a href="./">DLL 2021 R workshops</a></li>
      edit: https://github.com/darachm/dll-r/edit/main/%s
      download: ["html"] #,"pdf"]
      highlight: zenburn
    includes:
      after_body: footer.html
    #number_sections: false
    split_by: section+number
documentclass: book
github-repo: darachm/dll-r
description: "A living syllabus for the R section of DLL 2021, at Stanford"
#site: bookdown::bookdown_site
#biblio-style: apalike
#link-citations: yes
---

# Workshop introduction

## Workshop goals

This short 3-day course aims to give you a basic framework so you can work with someone 
effectively on a research project using R.

This framework includes getting you oriented with basic skills (e.g. using RStudio, documenting your process with R Markdown, basic data analysis and visualization) and empowering you to figure out how to accomplish research-related tasks in R.

## Structure and resources

### This syllabus and videos

We developed this website/document for your reference, as a living textbook and collection of "slides" and code snippets.

We have also made short teaching videos uploaded on Youtube that are embedded where appropriate on this site. These mini-lectures are intended to complement the text for those with different learning preferences.

You will be expected to progress through this website during asynchronous work time in this 3-day period. During synchronous meetings, you should plan to work directly with your peers and us on focused tasks. We will also be there to help with confusing or challenging topics that you want to discuss with someone live.

### Slack channel

While you are working in asynchronous sessions, or if you just need help during the program, there is a Slack channel available where you can go for ideas/help. The channel is called *#codingtroubleshooting* and should be accessible to you on the SSRP Slack server.

## Workshop expectations
1. Be respectful and compassionate.
2. Teach one another, learn from one another.
3. Aim for productive struggle.
+ You will learn best if you make a good faith effort before seeking help.
+ However, you should always seek help if you feel truly stuck.
4. Create your own sense of challenge.
+ Pick activities that you will learn and grow from.
+ If you don't find something challenging, make it challenging for yourself.

